DROP TABLE EMP_BOARDS CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEES CASCADE CONSTRAINTS;

CREATE TABLE EMP_BOARDS (
	ID NUMBER NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	EMPID NUMBER NOT NULL,
	CREATEDATE DATE NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYEES (
	EMPLOYEE_ID NUMBER NOT NULL,
	FIRST_NAME VARCHAR2(20) NOT NULL,
	LAST_NAME VARCHAR2(25) NOT NULL,
	EMAIL VARCHAR2(25) NOT NULL,
	PHONE_NUMBER VARCHAR2(20) NOT NULL,
	HIRE_DATE DATE NOT NULL,
	JOB_ID VARCHAR2(10) NOT NULL,
	SALARY NUMBER NOT NULL,
	COMMISSION_PCT DOUBLE NOT NULL,
	MANAGER_ID NUMBER NOT NULL,
	DEPARTMENT_ID NUMBER NOT NULL,
	PRIMARY KEY (EMPLOYEE_ID)
);
