-- 직원 테이블
SELECT * --*는 모든 컬럼
	FROM EMPLOYEES;	--스크립트 실행됐는지 확인해보기

SELECT EMPLOYEE_ID
	,  FIRST_NAME
	,  LAST_NAME
  FROM EMPLOYEES;

SELECT EMPLOYEE_ID
	,  FIRST_NAME
	,  LAST_NAME
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID >= 200;	--WHERE 조건식

SELECT EMPLOYEE_ID
	,  FIRST_NAME
	,  LAST_NAME
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID >= 200
   AND FIRST_NAME = 'Pat';	--AND 논리 연산자

SELECT EMPLOYEE_ID
	,  FIRST_NAME
	,  LAST_NAME
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID >= 200
    OR FIRST_NAME = 'Steven';	--OR 논리 연산자
   
    --문자열 리터럴은 홑따옴표
    --별칭은 쌍따옴표
    
SELECT EMPLOYEE_ID AS "사번"	--AS 별칭
	,  FIRST_NAME AS 이름
	,  LAST_NAME 성
	,  EMAIL "이메일 주소"	--띄어쓰기시 쌍따옴표 필수
  FROM EMPLOYEES;
 
SELECT EMPLOYEE_ID AS "사번"
	,  FIRST_NAME AS "이름"
	,  LAST_NAME AS "성"
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID >= 200;	--별칭으로 조회 불가능 "사번" >=200
 --해석 순서 1.FORM테이블 2.WHERE절 해석 3.SELECT절 해석
 --FORM절에 있는 테이블을 가져다가 WHERE절에 있는 조건들을 가져다가 SELECT 해석
 
SELECT FIRST_NAME || ' ' || LAST_NAME AS "이름"	--||결합 연산자 ''는 공백 만들기
	,  SALARY * 12 AS "연봉"
  FROM EMPLOYEES;

-- 조건절에서 사용하는 연산자
-- AND, OR, NOT, IN, NOT IN, BETWEEN ... AND
-- LIKE, IS NULL, IS NOT NULL
SELECT *
  FROM EMPLOYEES
 WHERE NOT EMPLOYEE_ID >= 200;

SELECT *
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID IN (200,201,202,203); --소괄호안에만 조회하기
 
 SELECT *
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID NOT IN (200,201,202,203); --소괄호안에만 조회하기
 
 SELECT *
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID BETWEEN 200 AND 203; --사이에 해당하는 값만 조회
 
 SELECT *
   FROM EMPLOYEES
  WHERE FIRST_NAME LIKE 'S%';
	
 SELECT *
   FROM EMPLOYEES
  WHERE FIRST_NAME LIKE '%en';

 SELECT *
   FROM EMPLOYEES
  WHERE FIRST_NAME LIKE '%ea%';

 SELECT *
   FROM EMPLOYEES
  WHERE FIRST_NAME LIKE '_____'; --_언더바 다섯글자인 것만 조회
  
 SELECT *
   FROM EMPLOYEES
  WHERE FIRST_NAME LIKE 'D____';
 
 SELECT *
   FROM EMPLOYEES
  WHERE JOB_ID LIKE '%#____' ESCAPE '#'; --ESCAPE \,& 옵션 설정에 맞춰서 LIKE도 바꿔준다
	
 SELECT *
   FROM EMPLOYEES
  WHERE JOB_ID NOT LIKE '%&____' ESCAPE '&';
 
 SELECT *
   FROM EMPLOYEES
  WHERE COMMISSION_PCT IS NULL; --NULL인것만 가져오기
  
 SELECT *
   FROM EMPLOYEES
  WHERE COMMISSION_PCT IS NOT NULL; --NULL이 아닌것만 가져오기
  
/* SELECT *
   FROM EMPLOYEES
  WHERE COMMISSION_PCT = NULL; 불가능!!
 */

 SELECT *
   FROM EMPLOYEES
  WHERE NOT EMPLOYEE_ID >= 200
     OR EMPLOYEE_ID = 100;
    
 SELECT *
   FROM EMPLOYEES
  WHERE NOT (EMPLOYEE_ID >= 200
     OR EMPLOYEE_ID = 100);
    
  
  
--부서 테이블
SELECT * FROM DEPARTMENTS;

--직급 테이블
SELECT * FROM JOBS;

--국가 테이블
SELECT * FROM COUNTRIES;

--국가별 테이블
SELECT * FROM LOCATIONS;

--대륙 테이블
SELECT * FROM REGIONS;
